### ISSUE TITLE
Low Cost Medical Device Search for OpenEMR Integration

### ISSUE THREAD

**Issue by woulschneider** [MatthewVita/fake-patient-web#2]
see https://github.com/openemr/openemr/issues/978

**Comment by MatthewVita** [comment]
@andremillet, looks like you entered the ticket into the wrong repo. I have moved it here: https://github.com/openemr/openemr/issues/978

Great work!

**Comment by woulschneider** [comment]
I have sent an email to Libelium salesman with a counter-offer, asking just a few components for testing purposes [EKG/heart rate monitor]. Also asked about the API used

**Comment by MatthewVita** [comment]
You're awesome!

As a side note, please use this thread instead: https://github.com/openemr/openemr/issues/978 (feel free to bookmark it... that's what I do to not lose my sanity lol)
